name: Update RTMA Outputs

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  generate_rtma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xarray==2023.6.0 metpy==1.6.2 matplotlib==3.8.0 cartopy numpy==1.26.4 netCDF4==1.5.7 scipy==1.12.0 siphon==0.9 protobuf==3.20.3

      - name: Delete old plots if they exist
        run: |
          rm -f plots/rtma/latest_t plots/rtma/latest_td
      
      - name: Run rtma.py
        run: python rtma.py
      
      - name: Commit and push RTMA changes
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          git stash push -u
          git pull --rebase origin main
          git stash pop
          git add plots/rtma/latest_t plots/rtma/latest_td
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update RTMA Plots"
            git push origin main
          fi
