name: Update HRRR Z Plots

on:
  schedule:
  - cron: '0 * * * *'  

jobs:
  update_hrrr_z_plots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib metpy==1.6.2 siphon==0.9 cartopy protobuf==3.20.3 numpy==1.26.4 netCDF4==1.5.7

      - name: Delete old plots if they exist
        run: |
          find plots/models/hrrr/reflectivity/ -name 'reflectivity_*.png' -exec rm {} +

      - name: Run hrrr_Z.py script
        run: python hrrr_Z.py

      - name: Commit and push changes
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          git add plots/models/hrrr/reflectivity/reflectivity_*.png
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update HRRR Z Plots"
            git push origin main
          fi
