name: Update RAP RH Forecast Sounding

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  generate_rtma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xarray==2023.6.0 metpy==1.6.2 matplotlib==3.8.0 cartopy numpy==1.26.4 netCDF4==1.5.7 siphon==0.9 protobuf==3.20.3 pandas==1.5.3
      - name: Delete old plots if they exist
        run: |
          find plots/models/rap/soundings/rh/ -name 'sounding_*.png' -exec rm {} +
      
      - name: Run rap_forecast_sounding_rh.py
        run: python rap_forecast_sounding_rh.py
    
      - name: Commit and push changes
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          # Stash any changes including untracked files
          git stash push -u
          # Pull with rebase
          git pull --rebase origin main
          # Pop the stash
          git stash pop
          # Add changes to staging area again
          git add plots/models/rap/soundings/rh/sounding_*.png
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            # Now commit and push
            git commit -m "Update RAP RH Soundings"
            git push origin main
          fi


